### ISSUE TITLE
Implement logic for resuming GraphChangeRequest queue after `lowCapacity` event pause

### ISSUE THREAD

**Issue by mattheworris** [AmplicaLabs/graph-service#34]
If a transaction fails because there is not enough capacity, an error is thrown, and the queue is paused.

When a new change request is received:
- [ ] Implement logic to check the current capacity level
  - [ ] If the capacity has been re-filled, resume the GraphChangeRequest queue
  - [ ] else set a timeout and re-check
- [ ] Implement logic to pause when a capacity limit for the graph-service has been reached
- [x] Add `CAPACITY_LIMIT` to the `env.template` file

**Comment by saraswatpuneet** [comment]
@mattheworris  we should also check a capacity limit allowed to be used by this service

https://github.com/AmplicaLabs/reconnection-service/blob/352aa768c7116625612413b7eb2cdd3037e80f48/env.template#L15
