### ISSUE TITLE
Add endpoint for removing dsnpIds/msaIds from webhook watch list

### ISSUE THREAD

**Issue by mattheworris** [AmplicaLabs/graph-service#77]
As a developer, I would like an endpoint to remove dnspIds/msaIds from the webhook watch list.

## Acceptance Criteria

- [ ] Implement a new endpoint `/api/unwatch-graphs` to remove ID's from the watch list

OR

- [ ] Refactor the existing `/api/watch-graphs` endpoint to handle removals from the list

**Comment by JoeCap08055** [comment]
Closed by #100
